<!-- ...................................................................... -->
<!-- HSML 1 Datatypes Module .............................................. -->
<!-- file: hsml1-datatype.mod
     
     This is HSML - Hyper Slide Markup Language, Version 1.
     
     Copyright 2004 Wakaba <w@suika.fam.cx>, All Rights Reserved.
     
     Permission to use, copy, modify and distribute this DTD and its
     accompanying documentation for any purpose and without fee is hereby
     granted in perpetuity, provided that the above copyright notice and
     this paragraph appear in all copies.  The copyright holders make no
     representation about the suitability of the DTD for any purpose.
     
     It is provided "as is" without expressed or implied warranty.
     
     Revision: 2004-11-08T10:28:26+00:00 (Generated by mkdtds/1.06)
     
     This DTD module is identified by the SYSTEM identifier:
     
       SYSTEM "http://suika.fam.cx/~wakaba/-temp/slide/schema/module/hsml1-datatype.mod"
     
     ...................................................................... -->

<!-- Datatypes

     This module defines containers for the datatypes.
-->

<!-- Class names.  More consideration needed for type. -->
<!ENTITY % hsml1.class.datatype "NMTOKENS">

<!-- IETF Language Tag -->
<!ENTITY % LanguageCode.datatype "CDATA">

<!-- A URI Reference -->
<!ENTITY % URI.datatype "CDATA">


<!-- end of hsml1-datatype.mod -->
