<!-- ...................................................................... -->
<!-- HSML 1 Internal Module ............................................... -->
<!-- file: hsml1-internal.mod
     
     This is HSML - Hyper Slide Markup Language, Version 1.
     
     Copyright 2004 Wakaba <w@suika.fam.cx>, All Rights Reserved.
     
     Permission to use, copy, modify and distribute this DTD and its
     accompanying documentation for any purpose and without fee is hereby
     granted in perpetuity, provided that the above copyright notice and
     this paragraph appear in all copies.  The copyright holders make no
     representation about the suitability of the DTD for any purpose.
     
     It is provided "as is" without expressed or implied warranty.
     
     Revision: 2004-11-08T10:28:26+00:00 (Generated by mkdtds/1.06)
     
     This DTD module is identified by the SYSTEM identifier:
     
       SYSTEM "http://suika.fam.cx/~wakaba/-temp/slide/schema/module/hsml1-internal.mod"
     
     ...................................................................... -->

<!-- Internal

       slideBody

     Information items for internal processing
-->

<!-- slideBody: Slide body - slide except note ......... -->

<!ENTITY % hsml1.slideBody.element "INCLUDE">
<![%hsml1.slideBody.element;[
<!ENTITY % hsml1.slideBody.content "(%hsml1.slide.qname;)">
<!ENTITY % hsml1.slideBody.qname "slideBody">
<!ENTITY % hsml1.slideBody.tagmin.start "-">
<!ENTITY % hsml1.slideBody.tagmin.end "-">
<![%sgml.tag.minimizable;[
<!ENTITY % hsml1.slideBody.tagmin "%hsml1.slideBody.tagmin.start; %hsml1.slideBody.tagmin.end;">
<!-- end of sgml.tag.minimizable -->]]>
<!ENTITY % hsml1.slideBody.tagmin "">
<!ELEMENT %hsml1.slideBody.qname; %hsml1.slideBody.tagmin; %hsml1.slideBody.content;>
<!-- end of hsml1.slideBody.element -->]]>

<!ENTITY % hsml1.slideBody.attlist "INCLUDE">
<![%hsml1.slideBody.attlist;[
<!ATTLIST %hsml1.slideBody.qname;
	%hsml1.common.attrib;>
<!-- end of hsml1.slideBody.attlist -->]]>


<!-- end of hsml1-internal.mod -->
