<!-- ...................................................................... -->
<!-- HSML 1.0 Document Model Module ....................................... -->
<!-- file: hsml10-model.mod
     
     This is HSML - Hyper Slide Markup Language, Version 1.0.
     
     Copyright 2004 Wakaba <w@suika.fam.cx>, All Rights Reserved.
     
     Permission to use, copy, modify and distribute this DTD and its
     accompanying documentation for any purpose and without fee is hereby
     granted in perpetuity, provided that the above copyright notice and
     this paragraph appear in all copies.  The copyright holders make no
     representation about the suitability of the DTD for any purpose.
     
     It is provided "as is" without expressed or implied warranty.
     
     Revision: 2004-11-08T10:28:21+00:00 (Generated by mkdtds/1.06)
     
     This DTD module is identified by the SYSTEM identifier:
     
       SYSTEM "http://suika.fam.cx/~wakaba/-temp/slide/schema/hsml10-model.mod"
     
     ...................................................................... -->

<!-- Document Model

     This model describes the groupings of element types that
     make up common content models.
-->

<!ENTITY % HeadOpts.mix "">

<!ENTITY % Edit.class "">

<!-- scripts and alternative content -->
<!ENTITY % Script.class "">

<!ENTITY % Misc.extra.class "">

<!-- neither block nor inline, and can
     essentially be used anywhere in the document body -->
<!ENTITY % Misc.class "%Edit.class;%Script.class;%Misc.extra.class;">

<!ENTITY % InlStruct.class "%h2.span.qname;">

<!ENTITY % hsml10.emphasis.class "%h2.em.qname;">

<!ENTITY % InlPhras.class "|%hsml10.emphasis.class;">

<!ENTITY % hsml10.vertical-align.class "%h2.sup.qname;|%h2.sub.qname;">

<!ENTITY % InlPres.class "|%hsml10.vertical-align.class;">

<!ENTITY % I18n.class "">

<!ENTITY % Anchor.class "">

<!ENTITY % InlSpecial.class "|%hsml10.seqNo.qname;">

<!ENTITY % InlForm.class "">

<!ENTITY % Ruby.class "|%h2.ruby.qname;">

<!ENTITY % Inline.extra.class "">

<!ENTITY % InlNoRuby.class "%InlStruct.class;%InlPhras.class;%InlPres.class;%I18n.class;%Anchor.class;%InlSpecial.class;%InlForm.class;%Inline.extra.class;">

<!-- includes all inline elements -->
<!ENTITY % Inline.class "%InlNoRuby.class;%Ruby.class;">

<!-- all inline elements, including %Misc.class; -->
<!ENTITY % Inline.mix "%Inline.class;%Misc.class;">

<!ENTITY % InlNoAnchor.class "%Inline.class;">

<!ENTITY % InlNoAnchor.mix "%InlNoAnchor.class;%Misc.class;">

<!ENTITY % NoRuby.content "(#PCDATA|%InlNoRuby.class;%Misc.class;)*">

<!ENTITY % List.class "%h2.ul.qname;|%h2.ol.qname;|%h2.nl.qname;|%h2.dl.qname;">

<!ENTITY % Heading.class "%h2.h.qname;">

<!ENTITY % Table.class "|%h2.table.qname;">

<!ENTITY % Form.class "">

<!ENTITY % Fieldset.class "">

<!ENTITY % BlkStruct.class "%h2.p.qname;|%h2.div.qname;">

<!ENTITY % BlkPhras.class "|%hsml10.fig.qname;">

<!ENTITY % BlkPres.class "">

<!ENTITY % BlkSpecial.class "%Table.class;%Form.class;%Fieldset.class;">

<!ENTITY % Block.extra.class "">

<!-- includes all block elements -->
<!ENTITY % Block.class "%BlkStruct.class;%BlkPhras.class;%BlkPres.class;%BlkSpecial.class;%Block.extra.class;">

<!-- includes all block elements plus %Misc.class; -->
<!ENTITY % Block.mix "%Heading.class;|%List.class;|%Block.class;%Misc.class;">

<!-- includes all text content, block and inline -->
<!ENTITY % Flow.mix "%List.class;|%Block.class;|%Inline.class;%Misc.class;">


<!-- end of hsml10-model.mod -->
